# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: dhingra_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: dhingra_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: dhingra_production
  pool: 5

cucumber:
  <<: *TEST
